apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-server
  namespace: mcp-servers
spec:
  to:
    kind: Service
    name: mcp-server
  port:
    targetPort: 80
  host: mcp-server.apps.<DOMAIN>
